# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'gpzu_tools_dialog_base.ui'
#
# Created by: PyQt4 UI code generator 4.12
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtCore import QCoreApplication

class Ui_gpzuToolsDialogBase(object):
    def setupUi(self, gpzuToolsDialogBase):
        gpzuToolsDialogBase.setObjectName("gpzuToolsDialogBase")
        gpzuToolsDialogBase.resize(378, 178)
        self.button_box = QtWidgets.QDialogButtonBox(gpzuToolsDialogBase)
        self.button_box.setGeometry(QtCore.QRect(180, 140, 191, 32))
        self.button_box.setOrientation(QtCore.Qt.Horizontal)
        self.button_box.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.button_box.setObjectName("button_box")
        self.formLayoutWidget = QtWidgets.QWidget(gpzuToolsDialogBase)
        self.formLayoutWidget.setGeometry(QtCore.QRect(10, 10, 361, 121))
        self.formLayoutWidget.setObjectName("formLayoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.formLayoutWidget)
        self.formLayout.setMargin(0)
        self.formLayout.setHorizontalSpacing(8)
        self.formLayout.setVerticalSpacing(10)
        self.formLayout.setObjectName("formLayout")
        self.label = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setWordWrap(False)
        self.label.setObjectName("label")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label)
        self.lineEdit = QtWidgets.QLineEdit(self.formLayoutWidget)
        self.lineEdit.setLayoutDirection(QtCore.Qt.RightToLeft)
        self.lineEdit.setInputMask("")
        self.lineEdit.setText("")
        self.lineEdit.setMaxLength(32783)
        self.lineEdit.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.lineEdit.setObjectName("lineEdit")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.lineEdit)
        self.label_2 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_2)
        self.comboBox = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox.setObjectName("comboBox")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.comboBox)
        self.label_3 = QtWidgets.QLabel(self.formLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.comboBox_2 = QtWidgets.QComboBox(self.formLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.comboBox_2)
        self.checkBox = QtWidgets.QCheckBox(gpzuToolsDialogBase)
        self.checkBox.setGeometry(QtCore.QRect(20, 140, 148, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        font.setBold(True)
        font.setItalic(True)
        font.setWeight(75)
        self.checkBox.setFont(font)
        self.checkBox.setObjectName("checkBox")

        self.retranslateUi(gpzuToolsDialogBase)
        #QtCore.QObject.connect(self.button_box, QtCore.SIGNAL("accepted()"), gpzuToolsDialogBase.accept)
        self.button_box.accepted.connect(gpzuToolsDialogBase.accept)
        #QtCore.QObject.connect(self.button_box, QtCore.SIGNAL("rejected()"), gpzuToolsDialogBase.reject)
        self.button_box.rejected.connect(gpzuToolsDialogBase.reject)
        QtCore.QMetaObject.connectSlotsByName(gpzuToolsDialogBase)

    def retranslateUi(self, gpzuToolsDialogBase):
        gpzuToolsDialogBase.setWindowTitle(QCoreApplication.translate("gpzuToolsDialogBase", "Загрузить участок карты"))
        self.label.setText(QCoreApplication.translate("gpzuToolsDialogBase", "ГПЗУ GID:"))
        self.label_2.setText(QCoreApplication.translate("gpzuToolsDialogBase", "Подключение к БД:"))
        self.label_3.setText(QCoreApplication.translate("gpzuToolsDialogBase", "Масштаб:"))
        self.checkBox.setText(QCoreApplication.translate("gpzuToolsDialogBase", "Ортофотплан"))

